[general]
import = [
"./catppuccin-mocha.toml"
]

[window]
padding.x = 10
padding.y = 10

decorations = "None"
decorations_theme_variant = "None"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font]
size = 15.0

[env]
TERM = "xterm-256color"
