set -ga terminal-overrides ",xterm-256color:Tc"

# prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -s escape-time 0
# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# split
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

set -g @catppuccin_window_left_separator ""
set -g @catppuccin_window_right_separator " "
set -g @catppuccin_window_middle_separator " | "
set -g @catppuccin_window_number_position "right"

set -g @catppuccin_window_default_fill "all"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory user host"
set -g @catppuccin_status_left_separator  " "
set -g @catppuccin_status_right_separator ""
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "no"

set -g @catppuccin_directory_text "#{pane_current_path}"

# theme
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux

# emptry bar to crate padding between tmux and terminal prompt
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[0]' ''
set -g status 2
