set -ga terminal-overrides ",xterm-256color:Tc"


# prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split
bind h split-window -h
bind v split-window -v
unbind '"'
unbind %

# windows navigation
bind Left previous-window
bind Right next-window

# pane navigation
bind-key -n C-M-Left select-pane -L
bind-key -n C-M-Right select-pane -R
bind-key -n C-M-Up select-pane -U
bind-key -n C-M-Down select-pane -D

set -g @catppuccin_window_left_separator "█"
set -g @catppuccin_window_right_separator "█ "
set -g @catppuccin_window_number_position "right"
set -g @catppuccin_window_middle_separator " | "

set -g @catppuccin_window_default_fill "none"
set -g @catppuccin_window_default_text "#W"

set -g @catppuccin_window_current_fill "all"
set -g @catppuccin_window_current_text "#W"

set -g @catppuccin_status_modules_right "directory host"
set -g @catppuccin_status_left_separator  "█"
set -g @catppuccin_status_right_separator "█"
set -g @catppuccin_status_fill "all"
set -g @catppuccin_status_connect_separator "yes"

# theme
run ~/.config/tmux/plugins/catppuccin/catppuccin.tmux
