# Sets user-defined palette palette = "catppuccin_mocha"

format = """$character"""
right_format = """$all"""

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[username]
disabled = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"

lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[buf]
symbol = " "

[directory]
read_only = " 󰌾"

[git_commit]
tag_symbol = '  '

[hostname]
disabled = true
ssh_symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "


[aws]
symbol = "  "

[bun]

[c]
symbol = " "

[cmake]
symbol = " "

[cmd_duration]

[cobol]

[conda]
symbol = " "

[crystal]
symbol = " "

[daml]

[dart]
symbol = " "

[deno]

[docker_context]
symbol = " "

[dotnet]

[elixir]
symbol = " "

[elm]
symbol = " "

[erlang]
symbol = "󰟔 "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]

[git_branch]
symbol = " "

[git_status]

[golang]
symbol = " "

[gradle]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[opa]

[openstack]

[os]

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[pulumi]

[purescript]

[python]
symbol = " "

[raku]

[red]

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[spack]

[sudo]

[swift]
symbol = " "

[terraform]

[time]

[vagrant]

[vlang]

[zig]

[solidity]
